modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="wpmoviemod"
version="1.0.0"
displayName="WeaponsPlus Movie Addon"
description="Ein Addon f√ºr die Hauptmod WeaponsPlus."

[[dependencies.wpmoviemod]]
modId="neoforge"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.wpmoviemod]]
modId="weaponsplusmod"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"
